### ISSUE TITLE
Can't compile code after update of diesel and diesel-async

### ISSUE THREAD

**Issue by maksalees** [niroco/diesel_async_migrations#5]
This code worked before:
```rust
use diesel_async::pg;
use lazy_static::lazy_static;

lazy_static! {
    static ref MIGRATIONS: diesel_async_migrations::EmbeddedMigrations =
        diesel_async_migrations::embed_migrations!();
}

pub async fn run_migrations(conn: &mut pg::AsyncPgConnection) -> anyhow::Result<()> {
    MIGRATIONS.run_pending_migrations(conn).await?;
    Ok(())
}
```
Now after updating diesel and diesel-async I get this error:
```
error[E0277]: the trait bound `AsyncPgConnection: DerefMut` is not satisfied
  --> crates/db/src/migrations.rs:10:39
   |
10 |     MIGRATIONS.run_pending_migrations(conn).await?;
   |                ---------------------- ^^^^ the trait `DerefMut` is not implemented for `AsyncPgConnection`
   |                |
   |                required by a bound introduced by this call
   |
   = help: the trait `diesel_async::AsyncConnection` is implemented for `diesel_async::pg::AsyncPgConnection`
   = note: required for `AsyncPgConnection` to implement `diesel_async::AsyncConnection`
note: required by a bound in `EmbeddedMigrations::run_pending_migrations`
  --> /home/maksales/.cargo/git/checkouts/diesel_async_migrations-a39f1733cd115917/11f331b/src/lib.rs:63:12
   |
61 |     pub async fn run_pending_migrations<C>(&self, conn: &mut C) -> Result<()>
   |                  ---------------------- required by a bound in this associated function
62 |     where
63 |         C: AsyncConnection<Backend = diesel::pg::Pg> + 'static + Send,
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `EmbeddedMigrations::run_pending_migrations`
```

**Comment by nicrosengren** [comment]
what version of this crate and dielse are you using?

**Comment by maksalees** [comment]
> what version of this crate and dielse are you using?

diesel 2.1.4, diesel-async 0.3.2 and this crate 0.11.0

**Comment by maksalees** [comment]
After updating diesel-async to 0.4.1, it worked.
